apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  namespace: cgmh-system
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.22.132.10
    path: "/nfs-data/mongodb/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  namespace: cgmh-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi