image: docker:latest
variables:
  DOCKER_DRIVER: overlay
services:
  - docker:dind
stages:
  - test
  - build
  - build_docker

.go_template: &go_template
  image: golang:1.11
  before_script:
  - export GO_PROJECT="$GOPATH/src/inwinstack/cgmh"
  - echo $GO_PROJECT
  - mkdir -p $GO_PROJECT
  - ln -srf $(pwd) $GO_PROJECT
  - export GO_PROJECT_PATH="$GO_PROJECT/$CI_PROJECT_NAME"
  - echo $GO_PROJECT_PATH
  - cd $GO_PROJECT_PATH
  - go get -u github.com/golang/dep/cmd/dep
  - make dep
  tags:
  - docker

test:
  stage: test
  <<: *go_template
  script:
    - make test

build:
  stage: build
  <<: *go_template
  script:
    - make

build_docker:
  stage: build_docker
  when: on_success
  tags:
  - docker
  only:
  - master@inwinstack/cgmh/apiserver
  - branches@inwinstack/cgmh/apiserver
  before_script:
  - apk add --no-cache make
  script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - make build_image 
    - make push_image
