
[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/ldap.v3"
  version = "v3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.2.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.2"

[prune]
  go-tests = true
  unused-packages = true
