apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: cgmh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: apiserver
        image: registry.gitlab.com/inwinstack/cgmh/apiserver:v0.2.1
        args:
        - --config=/etc/cgmh/config.yml
        volumeMounts:
        - name: config
          mountPath: "/etc/cgmh"
          readOnly: true
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        configMap:
          name: apiserver-config
          items:
          - key: config.yml
            path: config.yml    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
  namespace: cgmh-system
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apiserver
  sessionAffinity: None
  