apiVersion: v1
kind: ConfigMap
metadata:
  name: apiserver-config
  namespace: cgmh-system
data:
  config.yml: |
    global:
      listen: :8080
      jwtExpireHour: 1
      swagger: true
      monitorURL: http://172.20.3.56:32359
      # allowOrigins:
      # - https://foo.com
    ldap:
      protocol: tcp
      host: openldap:389
      bind:
        username: cn=admin,dc=cgmh,dc=org,dc=tw
        password: p@ssw0rd
      dn: dc=cgmh,dc=org,dc=tw
      userOU: accounts
    db:
      host: mongodb:27017
      source: admin
      user: root
      password: passw0rd
      name: CGMH
    admin:
      email: admin@inwinstack.com
      name: administrator
      password: r00tme
      agency: CGMH
      unit: 'AI Team'
      jobTitle: Manager
      phone: '0800-092-000'
    levels:
    - name: 'Level 0'
      gpuPrice: 0
      dayPrice: 0
      description: 'VIP User'
      default: false
    - name: 'Level 1'
      gpuPrice: 500
      dayPrice: 5
      description: 'Considerable User'
      default: false
    - name: 'Level 2'
      gpuPrice: 500
      dayPrice: 10
      description: 'Advanced User'
      default: false
    - name: 'Level 3'
      gpuPrice: 1000
      dayPrice: 10
      description: 'Medium User'
      default: true
    - name: 'Level 4'
      gpuPrice: -1
      dayPrice: 10
      description: 'Primary User'
      default: false