apiVersion: v1
kind: Namespace
metadata:
  name: cgmh-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apiserver-config
  namespace: cgmh-system
data:
  config.yml: |
    global:
      listen: :8080
      jwtExpireHour: 1
      swagger: true
      # allowOrigins:
      # - https://foo.com
    db:
      host: mongo-cluster:27017
      source: admin
      user: root
      password: passw0rd
      name: CGMH
    admin:
      email: admin@inwinstack.com
      name: administrator
      password: r00tme
      agency: CGMH
      unit: 'AI Team'
      jobTitle: Manager
      phone: '0800-092-000'
    levels:
    - name: 'Level 0'
      gpuPrice: 0
      dayPrice: 0
      description: 'VIP User'
      default: false
    - name: 'Level 1'
      gpuPrice: 500
      dayPrice: 5
      description: 'Considerable User'
      default: false
    - name: 'Level 2'
      gpuPrice: 500
      dayPrice: 10
      description: 'Advanced User'
      default: false
    - name: 'Level 3'
      gpuPrice: 1000
      dayPrice: 10
      description: 'Medium User'
      default: true
    - name: 'Level 4'
      gpuPrice: -1
      dayPrice: 10
      description: 'Primary User'
      default: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: cgmh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: apiserver
        image: registry.gitlab.com/inwinstack/cgmh/apiserver:v0.1.0
        args:
        - --config=/etc/cgmh/config.yml
        volumeMounts:
        - name: config
          mountPath: "/etc/cgmh"
          readOnly: true
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        configMap:
          name: apiserver-config
          items:
          - key: config.yml
            path: config.yml    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
  namespace: cgmh-system
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: apiserver
  sessionAffinity: None
  